### ISSUE TITLE
2.1. Set Up the Project 

### ISSUE THREAD

**Issue by tsvetkovpro** [tutsplus/start-building-modern-web-apps-with-react-and-redux#2]
Hi there, why on my windows 10 machine, don't work this script: 

>     "server": "cd public; live-server --port=1234 --entry-file=index.html"

![image](https://cloud.githubusercontent.com/assets/2004857/20298810/c37d2d6a-ab39-11e6-846b-20c0c99c68bc.png)

bun my public directory all ok: 

![image](https://cloud.githubusercontent.com/assets/2004857/20299034/db00fad8-ab3a-11e6-9008-0419c3205a2d.png)

[link to my repo](https://bitbucket.org/stasok/flashcard-app)

**Comment by Aloklok** [comment]
Hi tsvetkovpro,I ran into the same question days ago.It turned out that Windows cmd use ' & ' to connect two instructions ."server": "cd public & live-server --port=1234 --entry-file=index.html" would work.Hope it helps.
