### ISSUE TITLE
React issue with section 3.2

### ISSUE THREAD

**Issue by herrjosua** [tutsplus/start-building-modern-web-apps-with-react-and-redux#7]
While trying to complete the 3.2 section I'm getting a `Uncaught TypeError: React.createClass is not a function` error in my console. From doing a quick Google Search, I'm seeing that I need to add React. I check my sources tab and I'm seeing React, so I'm not sure why it giving me the error. I have pushed all of my code to my Github repo, which can be found [here](https://github.com/herrjosua/flashcard-app).

**Comment by herrjosua** [comment]
I'm not sure if this is the correct way to resolve it but this is how I did it. In the video we were told to use this line of code `const Sidebar = React.createClass()({`, but I changed it to `class Sidebar extends React.Component {` due to the fact that `React.createClass` is deprecated in the latest release of React.

**Comment by a-eid** [comment]
@herrjosua yes the course is a bit outdated. you need to use es6 `class` syntax.

**Comment by herrjosua** [comment]
Using the class syntax resolved this issue.
